apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
  namespace: langfuse
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: langfuse
    app.kubernetes.io/name: clickhouse
    shard: "0"
  ports:
    - name: http
      port: 8123
      targetPort: 8123
      nodePort: 30123
      protocol: TCP
    - name: tcp
      port: 9000
      targetPort: 9000
      nodePort: 30900
      protocol: TCP
